language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4


matrix:
  allow_failures:
    - php: 7.0

services: mysqlL


before_script:
  - mysql -e 'create database myapp_test;'
  - cp  app/config/parameters.yml.dist app/config/parameters.yml
  - cp .travis.parameters_test.pgsql.yml app/config/parameters_test.yml
  - cp  app/phpunit.xml.dist app/phpunit.xml
  - composer install --dev --no-interaction


script: phpunit  --configuration app/phpunit.xml


