#!/bin/bash
cp /vagrant/vagrant/parameters.yml /vagrant/app/config/parameters_test.yml
rm -r /vagrant/app/cache/prod/*
rm -r /vagrant/app/cache/dev/*
cd /vagrant
php app/console cache:warmup --env=prod
php app/console cache:warmup --env=dev
phpunit -c app/phpunit.frontend.xml
