######################################################################## Home Page

questionkey_home:
    pattern:  /
    defaults: { _controller: QuestionKeyBundle:Index:index }
    methods:  [GET]

######################################################################## API 1

questionkey_api_1_tree_data_json:
    pattern:  /api/v1/tree/{treeId}/data.json
    defaults: { _controller: QuestionKeyBundle:API1Tree:dataJSON }
    methods:  [GET]

questionkey_api_1_tree_data_jsonp:
    pattern:  /api/v1/tree/{treeId}/data.jsonp
    defaults: { _controller: QuestionKeyBundle:API1Tree:dataJSONP }
    methods:  [GET]

questionkey_api_1_visitorsession_action_json:
    pattern:  /api/v1/visitorsession/action.json
    defaults: { _controller: QuestionKeyBundle:API1VisitorSession:actionJSON }
    methods:  [GET]

questionkey_api_1_visitorsession_action_jsonp:
    pattern:  /api/v1/visitorsession/action.jsonp
    defaults: { _controller: QuestionKeyBundle:API1VisitorSession:actionJSONP }
    methods:  [GET]

######################################################################## Public Tree pages

questionkey_tree_demo:
    pattern:  /tree/{treeId}/demo
    defaults: { _controller: QuestionKeyBundle:Tree:demo }
    methods:  [GET]

questionkey_tree_version_preview_demo:
    pattern:  /tree/{treeId}/version/{versionId}/code/{code}/demo
    defaults: { _controller: QuestionKeyBundle:TreeVersionCode:demo }
    methods:  [GET]

questionkey_tree_version_preview_data_json:
    pattern:  /tree/{treeId}/version/{versionId}/code/{code}/data.json
    defaults: { _controller: QuestionKeyBundle:TreeVersionCode:dataJSON }
    methods:  [GET]

######################################################################## Start Admin!

questionkey_admin:
    pattern:  /admin
    defaults: { _controller: QuestionKeyBundle:Admin:index }
    methods:  [GET]

######################################################################## Admin Tree

questionkey_admin_tree_list:
    pattern:  /admin/tree
    defaults: { _controller: QuestionKeyBundle:AdminTreeList:index }
    methods:  [GET]

questionkey_admin_tree_new:
    pattern:  /admin/tree/new
    defaults: { _controller: QuestionKeyBundle:AdminTreeNew:index }
    methods:  [GET,POST]

questionkey_admin_tree_new_import:
    pattern:  /admin/tree/new/import
    defaults: { _controller: QuestionKeyBundle:AdminTreeNew:import }
    methods:  [GET,POST]

questionkey_admin_tree_show:
    pattern:  /admin/tree/{treeId}
    defaults: { _controller: QuestionKeyBundle:AdminTree:index }
    methods:  [GET]

questionkey_admin_tree_edit:
    pattern:  /admin/tree/{treeId}/edit
    defaults: { _controller: QuestionKeyBundle:AdminTreeEdit:edit }
    methods:  [GET,POST]


questionkey_admin_tree_stats:
    pattern:  /admin/tree/{treeId}/stats
    defaults: { _controller: QuestionKeyBundle:AdminTree:stats }
    methods:  [GET]

questionkey_admin_tree_version_published_list:
    pattern:  /admin/tree/{treeId}/versionpublished
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionPublishedList:index }
    methods:  [GET]

questionkey_admin_tree_version_list:
    pattern:  /admin/tree/{treeId}/version
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionList:index }
    methods:  [GET]

######################################################################## Admin Tree Version

questionkey_admin_tree_version_show:
    pattern:  /admin/tree/{treeId}/version/{versionId}
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:index}
    methods:  [GET]

questionkey_admin_tree_version_run:
    pattern:  /admin/tree/{treeId}/version/{versionId}/run
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:run}
    methods:  [GET]

questionkey_admin_tree_version_edit:
    pattern:  /admin/tree/{treeId}/version/{versionId}/edit
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:edit}
    methods:  [GET,POST]

questionkey_admin_tree_version_publish:
    pattern:  /admin/tree/{treeId}/version/{versionId}/publish
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:publish}
    methods:  [GET,POST]

questionkey_admin_tree_version_new_version:
    pattern:  /admin/tree/{treeId}/version/{versionId}/newVersion
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:newVersion}
    methods:  [GET,POST]

questionkey_admin_tree_version_data_json:
    pattern:  /admin/tree/{treeId}/version/{versionId}/data.json
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:dataJSON }
    methods:  [GET]

questionkey_admin_tree_version_graph:
    pattern:  /admin/tree/{treeId}/version/{versionId}/graph
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:graph }
    methods:  [GET]

questionkey_admin_tree_version_export:
    pattern:  /admin/tree/{treeId}/version/{versionId}/export
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:export }
    methods:  [GET]

questionkey_admin_tree_version_stats:
    pattern:  /admin/tree/{treeId}/version/{versionId}/stats
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:stats }
    methods:  [GET]

questionkey_admin_tree_version_graph_savecurrent:
    pattern:  /admin/tree/{treeId}/version/{versionId}/graph/save/current
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:graphSaveCurrent }
    methods:  [POST]

questionkey_admin_tree_version_get_preview_link:
    pattern:  /admin/tree/{treeId}/version/{versionId}/getPreviewLink
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:getPreviewLink }
    methods:  [GET]

######################################################################## Admin Variables

questionkey_admin_tree_version_variable_new:
    pattern:  /admin/tree/{treeId}/version/{versionId}/newVariable
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:newVariable}
    methods:  [GET,POST]

questionkey_admin_tree_version_variable_list:
    pattern:  /admin/tree/{treeId}/version/{versionId}/variable
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:variableList}
    methods:  [GET,POST]

questionkey_admin_tree_version_variable_show:
    pattern:  /admin/tree/{treeId}/version/{versionId}/variable/{variableId}
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionVariable:index}
    methods:  [GET,POST]

######################################################################## Admin Library Content

questionkey_admin_tree_version_library_content_new:
    pattern:  /admin/tree/{treeId}/version/{versionId}/newLibraryContent
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:newLibraryContent}
    methods:  [GET,POST]

questionkey_admin_tree_version_library_content_list:
    pattern:  /admin/tree/{treeId}/version/{versionId}/library/content
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:libraryContentList}
    methods:  [GET,POST]

questionkey_admin_tree_version_library_content_show:
    pattern:  /admin/tree/{treeId}/version/{versionId}/library/content/{contentId}
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionLibraryContent:index}
    methods:  [GET,POST]

######################################################################## Admin Nodes


questionkey_admin_tree_version_node_list:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:nodeList }
    methods:  [GET]

questionkey_admin_tree_version_node_list_end_nodes:
    pattern:  /admin/tree/{treeId}/version/{versionId}/nodeEndNodes
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:nodeListEndNodes }
    methods:  [GET]

questionkey_admin_tree_version_node_list_unreachable_nodes:
    pattern:  /admin/tree/{treeId}/version/{versionId}/nodeUnreachableNodes
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:nodeListUnreacheableNodes }
    methods:  [GET]

questionkey_admin_tree_version_node_new:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/new
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersion:newNode}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_show:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:index}
    methods:  [GET]

questionkey_admin_tree_version_node_edit:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/edit
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:edit}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_delete:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/delete
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:delete}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_make_start_node:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/makeStart
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:makeStart}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_stacktrace:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/stacktrace
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:stacktrace}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_preview:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/preview
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:preview}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_preview_body_html:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/preview/bodyHTML
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:previewBodyHTML}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_stats:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/stats
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:stats}
    methods:  [GET]

questionkey_admin_tree_version_node_library_content_new:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/addLibraryContent
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:addLibraryContent}
    methods:  [GET, POST]

######################################################################## Admin Node Options

questionkey_admin_tree_version_node_option_new:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/option/new
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNode:newOption}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_option_show:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/option/{optionId}
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNodeOption:index}
    methods:  [GET]

questionkey_admin_tree_version_node_option_edit:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/option/{optionId}/edit
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNodeOption:edit}
    methods:  [GET,POST]

questionkey_admin_tree_version_node_option_delete:
    pattern:  /admin/tree/{treeId}/version/{versionId}/node/{nodeId}/option/{optionId}/delete
    defaults: { _controller: QuestionKeyBundle:AdminTreeVersionNodeOption:delete}
    methods:  [GET,POST]

######################################################################## Admin Sessions

questionkey_admin_visitor_session_list:
    pattern:  /admin/visitorsession
    defaults: { _controller: QuestionKeyBundle:AdminVisitorSessionList:index }
    methods:  [GET]

questionkey_admin_visitor_session_show:
    pattern:  /admin/visitorsession/{sessionId}
    defaults: { _controller: QuestionKeyBundle:AdminVisitorSession:index }
    methods:  [GET]

questionkey_admin_visitor_session_ran_tree_show:
    pattern:  /admin/visitorsession/{sessionId}/ranTreeVersion/{ranTreeVersionId}
    defaults: { _controller: QuestionKeyBundle:AdminVisitorSessionRanTreeVersion:index }
    methods:  [GET]

######################################################################## Logged In users

questionkey_you:
    pattern:  /you
    defaults: { _controller: QuestionKeyBundle:Index:you }
    methods:  [GET]
